### PR TITLE
Fix for RemoteTech v1.8.13

### PR DESCRIPTION
**Pull request by PiezPiedPy**
I added a new method to RT's API for Kerbalism and it appears to have broken CC.
Here is the fix needed 😉

### CODE REVIEW

**Comment by PiezPiedPy** [comment]
Here is a build with the fix https://www.dropbox.com/s/3vhw8kteydjzwk2/CC_RemoteTech.dll?dl=0

**Comment by 7ranceaddic7** [comment]
I have a question about this fix.  I ran across the exact same problem and called it up in MonoDevelop.

MD made this suggestion:

            public bool PowerShutdownFlag { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }

And all build properly.

Are these essentially the same fixes?

P.S. I know NOTHING (seriously, nothing) about C#.

**Comment by 7ranceaddic7** [comment]
Oh, so it's like putting a break in the code as a reminder?

**Comment by rsparkyc** [comment]
> Oh, so it's like putting a break in the code as a reminder?

Sort of, but it's actually throwing that as an exception, which if not caught, will break the code.  https://docs.microsoft.com/en-us/dotnet/api/system.notimplementedexception?redirectedfrom=MSDN&view=netframework-4.7.2

**Pull request merged**
